language: node_js
node_js:
  - "6.11.5"

before_install:
  - npm -g i firebase-tools
  - npm -g i typescript
  - npm -g i tslint

install:
  - cd functions
  - npm install

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
