language: node_js
node_js:
  - "6.11.5"

before_install:
  - npm -g i firebase-tools
  - npm -g i typescript
  - npm -g i tslint
  - cd functions
  - npm install
  - cd ..

install:
  - echo "Time to install the application packages"
  - cd functions
  - npm run lint
  - npm run build
  - cd ..

before_script:
  - echo "Time to deploy..."

script:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

after_success:
  - echo "Deployed... to firebase."